# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "deps"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
      timezone: "UTC"

  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "deps"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"
    groups:
      analyzers:
        patterns:
          - "StyleCop.Analyzers.Unstable"
          - "SonarAnalyzer.CSharp"
          - "Roslynator.Analyzers"
          - "MustUseRetVal"
      aspire:
        patterns:
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
      entity-framework:
        patterns:
          - "*EntityFrameworkCore*"
          - "EFCore.*"
          - "dotnet-ef"
      ms-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      fluent-validation:
        patterns:
          - "*FluentValidation*"
