# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
    commit-message:
      prefix: "chore(deps)"
    groups:
      aspire:
        patterns:
          - "Aspire.*"
          - "CommunityToolkit.Aspire.*"
      entity-framework:
        patterns:
          - "*EntityFrameworkCore*"
          - "EFCore.*"
          - "dotnet-ef"
      ms-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      fluent-validation:
        patterns:
          - "*FluentValidation*"
